### ISSUE TITLE
Add the folder where the CMake package config are generated.

### ISSUE THREAD

**Issue by Adnn** [ShredEagle/shred_conan_base#2]
So they can be found in the build tree (workspace/editable mode).

The setting seems to be: ` self.cpp.source.builddirs`.

**Comment by FranzPoize** [comment]
@Adnn seems outdated ?

**Comment by Adnn** [comment]
Actually, I do not understand the impact of these files. They seem to be picked up by some conan commands. (For example, if you have several different build configured in separate subfolders, running `conan build` seems to pick up the last one, which overwrote those files).

So: I do not know, sorry.

**Comment by Adnn** [comment]
I think so too, now they are cleanly located.
